name: 'Translate'
description: 'Automatic translation using GPT'
inputs:
  folder-to-translate:  # id of input
    description: 'Path to folder to translate'
    required: true
    default: 'docs/'
  language:  # id of input
    description: 'Language to translate to'
    required: true
    default: 'es'
  output-folder:
    description: "Output Folder"
    default: 'docs_translated/'

runs:
  using: "composite"
  steps:
    - run: echo Folder to translate ${{ inputs.folder-to-translate }}.
      shell: bash
    - run: |
        python -m pip install --upgrade pip
        python -m pip install gpt-translate
      shell: bash
    - run: gpt_translate.folder ${{ inputs.folder-to-translate }} ${{ inputs.output-folder }} --language ${{ inputs.language }}
      shell: bash
